### ISSUE TITLE
Support for OSX?

### ISSUE THREAD

**Issue by juancrobles** [merken/Prise#14]
Hi I am looking for cross platform plugin systems for .net core and find yours, but trying the example with avalonia on OS X Mojave get the error "Unhandled exception. Prise.PrisePluginException: Platform is not supported"... so my question is, what is necesary to make osx supported?

**Comment by merken** [comment]
Hi,

The main reason OS X is not yet supported is that I'm not in possession of a Mac, so I can't really test this.

I will try to get a VM running using High Sierra and test my changes, they should be easy to apply.

**Comment by juancrobles** [comment]
Hi, that'll be great...
Any way that I can help please don't hesitate, I am not expert in C#, just begining

**Comment by Duan112358** [comment]
I wonder if fixed some path problem in `RuntimePlatformContext.cs`, or OSX will be got supported

``` csharp
if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
     runtimeBasePath = "/usr/local/share/dotnet/shared";
```

**Comment by merken** [comment]
Supporting OSX would be a matter of the following changes to the RuntimePlatformContext.cs file.

Returning possible candidate files when retrieving dependencies:
![image](https://user-images.githubusercontent.com/187081/80678178-b72dbe80-8aba-11ea-9854-98bf8fbc7d27.png)

As well as providing the platform-specific file extensions:
![image](https://user-images.githubusercontent.com/187081/80678232-d3316000-8aba-11ea-93db-57224aae9745.png)

And lastly, providing the base path for the installed runtime(s):
![image](https://user-images.githubusercontent.com/187081/80678277-e9d7b700-8aba-11ea-9ba7-18532331f26e.png)

Since I have no access to a machine running OSX, I cannot fullytest this. 
**I've created a branch called 'osx' that implements this, would someone be able to test this on macOS ?**

https://github.com/merken/Prise/blob/osx/src/Prise/Platform/RuntimePlatformContext.cs

I'm assuming the dotnet runtime path is **/usr/local/share/dotnet/shared/**, as I can see here :https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-macos

**Comment by Duan112358** [comment]
@merken , I changed as you described above, and it run smoothly on OSX now.

**Comment by merken** [comment]
@Duan112358 Thanks for your investigation!
1.6.1 is now live with support for OSX: https://www.nuget.org/packages/Prise/1.6.1
