### ISSUE TITLE
Loading plugins on runtime

### ISSUE THREAD

**Issue by VitorScheffer** [merken/Prise#17]
It's possible load plugins on runtime ?
I was thinking of a 'marketplace' where my customers can select and install the plugins without the need of restarting the app

Let me know if that is possible, thanks!

**Comment by merken** [comment]
Hi Vitor,

Yes this is possible.
Prise would then be loaded as a singleton service (1 loader per host).
I've already implemented this in an MVC application:
http://prisemvc.mrkn.be
https://github.com/merken/Prise.Examples/tree/master/MVCPlugins

I'm working on porting to .NET 5 first, after I will update docs in order to make this information as available as possible.

Feel free to ask any questions regarding your setup.

Cheers,
M

**Comment by VitorScheffer** [comment]
Thats great!,

I'm trying to use with .net core 3.1 (Host in he example, Host2 throws error) but the function `assemblyScanner.Scan();` returns nothing, i am missing something?
 
I Have tried to change the folder, but still no plugins found

**Comment by merken** [comment]
Hi Vitor,

Plugins are loaded from the **bin/Debug/netcoreapp3.1/Plugins** directory if this folder is empty, no results will be loaded.

You will first need to ```dotnet publish``` the following projects:

- OrdersAPIControllerPlugin
- ProductsAPIControllerPlugin
- TwitterWidgetPlugin
- WeatherWidgetPlugin

Copy the results from the **bin/debug/netcoreapp3.0/publish** directories from each of the plugins into the **bin/Debug/netcoreapp3.1/Plugins** directory of the MyHost directory.

Your Plugins directory of the MyHost application will look like this:
![image](https://user-images.githubusercontent.com/187081/80523593-99633b00-898e-11ea-84ce-f17aa1cc54fa.png)

Don't worry about cleaning or rebuilding the MyHost project, the Plugins folder will not get deleted by a dotnet clean or dotnet build.

After you copied the plugins, you should be able to run the MyHost project and detect the plugins.

This entire procedure is scripted by a build.cake file using Cake build: https://cakebuild.net
To automate this, install Cake via Chocolatey and navigate to the MVCPlugins directory, where the cake.build file is located. Open a CMD/Bash/Powershell prompt here and type ```cake``` and hit <enter>. This will take care of publishing the plugins and copying the output to the MyHost application.
![image](https://user-images.githubusercontent.com/187081/80523976-32925180-898f-11ea-97e4-70dd744a416e.png)

**All examples in this repository contain a cake.build file to do this.**

Hope to have helped you this way.
I will look into the MyHost2 now.
Kr,
Maarten

**Comment by merken** [comment]
I validate that MyHost2 is running correctly, keep in mind this is **slow**.
![image](https://user-images.githubusercontent.com/187081/80524393-d1b74900-898f-11ea-9a6a-1b96b6de2282.png)

This is expected behavior in .NET Core 2.x. We're missing some key-api's that make efficient assembly scanning possible.

**Comment by VitorScheffer** [comment]
Hi Merken,

Thanks again, i was putting only the projects DLLs in the plugin folder 
now work's just fine awsome project!

now i will implement in my multi tenancy application, but i think that is gone solve a lot of my problems
