### ISSUE TITLE
How to inject ILogger<T>

### ISSUE THREAD

**Issue by kapilbhavsar** [merken/Prise#49]
How can I inject type ILogger&lt;MyService&gt; in MyService class

**Comment by merken** [comment]
Hi,

I assume you're talking about injecting ILogger into a plugin or a service inside a plugin ?
I would advise **not to use ILogger**, but to provide an **abstraction** that is defined in your **Contract**

Something like:
```
public interface IPluginLogger
{
void LogInformation(string message);
void LogError(string message);
}
```

In the **Host** you must provide the implementation like an Adapter pattern, meaning you wrap the ILogger inside the IPluginLogger (or MyPluginLogger)

Just remember to use ILogger instead of ILogger<T>, you will lose some metadata, but this way, backwards compatibility is guaranteed.

There's an example of this in the docs at **Host Services** https://merken.github.io/Prise/#/?id=%f0%9f%8e%a9-host-services
